name: codeteach_web
description: A web-based coding education platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  go_router: ^14.3.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  logging: ^1.2.0
  # Replacing url_strategy with this package
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - .env
